ДЗ раздела 2.Разметка
htmlacademy-adaptive/1872141-cat-energy-1 pull request #2
Opened 2023-10-17 13:38 UTC by Vital-Sh

Выполнил разметку всех страниц. В комментариях в коде написал несколько уточнений и вопросов.

2023-10-18 18:53 UTC, andreysgra requested changes

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +      <h1 class="visually-hidden">У нас широкий выбор товаров питания для животных.</h1>
Под заголовок первого уровня очень хорошо подходит текст "Каталог продукции" который есть в макете (его вы разметили с помощью `h2`). Поэтому не стоит добавлять собственный `h1` с классом `visually-hidden`. И, как правило, `h1` чаще всего используется внутри `main`, то есть в содержательной части страницы.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +          <!--Не нравится мне второе имя класса которое придумал у списка, но мне же нужно показать, что этот список является элементом блока navigation и что он является отдельным блоком. Поэтому по
Оставьте пока как есть. В дальнейшем будет более понятно, нужен ли ему этот класс вообще.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +      <h2 class="catalog-main-container__title">Каталог продукции</h2>
`h2` стоит сменить на `h1` (причину описал выше).

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +      <!--Не уверен нужно ли тут миксование классов списка, а так же обёртка и отдельный заголовок...-->
Необходимость миксования классов / дополнительных обёрток становится более очевидным при стилизации страницы, в частности при построении сеток. На данном этапе лучше упростить разметку.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +        <!--Вопрос по макету... Должно ли что-то происходить при нажатие на картинку (приближение, попап и т.п.)?-->
Ответ на ваш вопрос в этом пункте ТЗ [https://up.htmlacademy.ru/adaptive-individual/1/project/cat-energy#cat-energy-6-1](https://up.htmlacademy.ru/adaptive-individual/1/project/cat-energy#cat-energy-6-1). Ну а по стилям ничего в стайлгайде не указано.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +            <dt class="goods-description__value">700</dt>
Ошибка валидации HTML. Неправильный порядок следования тегов `dd`, `dt`. Сначала должен идти `dt`, а потом `dd`. [https://webref.ru/html/dl](https://webref.ru/html/dl). Исправить нужно везде.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +              <a class="site-nav-list__link site-nav-list__item--active" href="catalog.html">
Класс `site-nav-list__item--active` является модификатором элемента `site-nav-list__item`, но в теге использован класс `site-nav-list__link`. Проверить можно [здесь](https://webref.ru/html/dl).

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +          <button class="card__button" type="button">заказать</button>
Ссылка. В реальном сайте будет вести на страницу заказа.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +            <!--Значёк рубля будет реализован изображением, или можно вставить текстом из макета?-->
Текстом.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +      <!--Решил вынести кнопки "Ещё" из списка, чтобы у людей, которые пользуются читалками, имелась возможность сразу открыть более полный список продуктов, а не толкьо после того, как прослушают ин
Решение с точки зрения разметки правильное, так как в список помещаются схожие сущности, а блок "показать ещё" не имеет общего с карточками товаром. Но тут возникает другой вопрос - вопрос построения сетки. Как будете размещать этот блок, если он находится в одном ряду с другими карточками?

В таком случае более логично обойтись без списка для карточек. Общий контейнер - `div` или `section`, а саму карточку можно оформить тегом `article`.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +      <article class="catalog-main-container__show-more show-more-wrapper">
А вот здесь `article` использовать не стоит.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +        <button class="show-more-wrapper__button-more" type="button">Показать еще 100500 товаров</button>
Это не кнопка, а поясняющий текст. Тег `p`.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +            </dl>
Такая же ошибка валидации HTML про которую писал в карточке товара.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +            <button class="additional-card__button">заказать</button>
Ссылка. Ведёт на страницу заказа.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +        <!--Вопрос по макету. Когда должен ещё отображаться товар? После нажатия на крест, на текст "Показать еще 100500 товаров", текст "На самом деле вкусов гораздо больше!", или это всё одна больш
Следующая порция карточек отображается после нажатия на кнопку "показать все". Но лично мне кажется, что было бы логично "крест" разметить кнопкой нажатие по которой приводило бы к добавлению новой порции. Из данного макета это не совсем понятно.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +      <aside class="catalog-main-container__promo promo-gift">
`aside` здесь не подходит.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +        <!--Вопрос по макету. Это просто картинка с рекламой? Ссылка на страницу, где все товары в корзине? Или кнопка, которая добавляет все товары в корзину? Если кнопка, то при нажатии на что она
Просто фоновая картинка.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +        <h2 class="visually-hidden">Как нас найти?</h2>
Не кнопка, просто текст в теге `p`.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +        <iframe class="contacts__map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6036257198189!2d30.320472477349337!3d59.938719162093555!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3
`iframe` нужен, если в дальнейшем не собираетесь делать более сложную реализацию через API сервиса карт. Ещё понадобится обёртка `div` чтобы разместить статическое изображение карты.

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +        </a>
А зачем здесь две ссылки?

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +        <ul class="add-list-wrapperr__additional-list additional-cards">
`add-list-wrapperr__additional-list` ошибка именования класса по БЭМ,

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +      <aside class="main-container__contacts contacts">
`main-container__contact` ошибка именования класса по БЭМ,

2023-10-18 18:53 UTC, andreysgra commented on source/catalog.html
> +    <footer class="mail-footer">
```suggestion
    <footer class="main-footer">
```

2023-10-18 18:53 UTC, andreysgra commented on source/form.html
> +    <h1 class="visually-hidden">У нас широкий выбор товаров питания для животных.</h1>
"Подбор программы" - это `h1`.

2023-10-18 18:53 UTC, andreysgra commented on source/form.html
> +    <!--Возможно нет смысла на каждую страницу задавать разные классы для main. Пока назвал их по-разному, если в процессе вёрстки страниц не будет различий для main, то название класса будет одинако
Конечно нет смысла задавать разные классы. `main` одной страницы ничем не отличается от `main` другой.

2023-10-18 18:53 UTC, andreysgra commented on source/form.html
> +      <h1 class="visually-hidden">Кэт энерджи - заботу о весе вашего любимца мы берём на себя.</h1>
Не нужен этот `h1`.

2023-10-18 18:53 UTC, andreysgra commented on source/form.html
> +      <h2 class="form-main-container__title">Подбор программы</h2>
`h2` заменить на `h1`.

2023-10-18 18:53 UTC, andreysgra commented on source/form.html
> +      <!--Не нашёл в описании задания и критериях заполнение для action, поэтому взял эту информацию из предыдущего курса.-->
И правильно сделали.

2023-10-18 18:53 UTC, andreysgra commented on source/form.html
> +            <input class="cat-information__age-input" type="text" name="cat-age" placeholder="7" required>
Пометки в виде `*` нет, значит поле не обязательно к заполнению.

2023-10-18 18:53 UTC, andreysgra commented on source/form.html
> +          <!--У нас в макете 3 одинаковых по оформлению элемента отличаются только текстом...
Дополнительные классы могут понадобится при стилизации, так что это вполне оправдано. Но добавлять класс только ради того, чтобы обозначить элемент блока, не нужно. Не обязательно вложенный HTML элемент должен быть БЭМ элементом какого-то БЭМ блока.

2023-10-18 18:53 UTC, andreysgra commented on source/form.html
> +            <input class="owner-information__phone-number-input" type="text" name="owner-phone-number" placeholder="8 (960) 900-60-90" required>
По поводу типа полей: [https://up.htmlacademy.ru/adaptive-individual/1/project/cat-energy#cat-energy-5-2](https://up.htmlacademy.ru/adaptive-individual/1/project/cat-energy#cat-energy-5-2)

2023-10-18 18:53 UTC, andreysgra commented on source/img/index/Fat-cat.png
Заглавная буква в названии файла.

2023-10-18 18:53 UTC, andreysgra commented on source/form.html
> +                <span class="control_label">сахарозаменитель</span>
Ошибки именования класса по БЭМ,

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +        <p class="promo-wrapper__intro">Функциональное питание для котов</p>
Текст вполне подходит под `h1`.

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +    <h1 class="visually-hidden">У нас широкий выбор товаров питания для животных.</h1>
А этот `h1` можно убрать.

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +        <!--Я правильно понял, что при переключении между разными устройствами положение кнопки будет меняться наложение поверх изображения и дублировать её (как дублировали при вёрстке "Барбершопа")
Дублирование запрещено критерием [Б4](https://up.htmlacademy.ru/adaptive-individual/1/criteries#b4).

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +      <h1 class="visually-hidden">Кэт энерджи - заботу о весе вашего любимца мы берём на себя.</h1>
Этот `h1` убрать. На странице только один `h1`.

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +      <section class="main-container__about-weight servic">
Что за класс такой `servic`? ;-)

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +          <img class="weight-loss__image" src="img/index/silhouette-cat-slim.svg" width="36" height="50" alt="Силуэт сидящей египетской кошки в ошейнике">
Это декоративное изображение.

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +          <img class="weight-gain__image" src="img/index/silhouette-panther.svg" width="67" height="28" alt="Силуэт идущей пантеры">
Это декоративное изображение.

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +      <!--Неуверен на счёт правильного выбора тега... Возможно тут использовать тег article? По идее этот блок можно на любую другую страницу поместить, но тогда не сосвсем будет понятен смысл текста
Если смысл текста зависит от контекста страницы, то блок нельзя считать самостоятельным и следовательно `article` не подходит.

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +          <!--Я же правильно понимаю, что в этом слайдере порядок сладдов фиксирован и важен? Или тут всё же использовать ненумерованный?-->
Нет, порядок не важен.

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +          <!--Данный слайдер переключается не кнопками, а ползунком... Нужно ли сейчас заниматься вёрсткой этого элемента, или работа со слайдером будет продолжена в следующих разделах?-->
Да, нужно уже сейчас. Разметка: кнопка (то, что круг) и `div` (то, что полоса).

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +            <dt class="service-result-list_benefit">
Ошибка именования класса по БЭМ.

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +              <img class="slider__image_before" src="img/index/Fat-cat.png" width="280" height="256" alt="Толстый кот">
Ошибка именования класса по БЭМ.

2023-10-18 18:53 UTC, andreysgra commented on source/index.html
> +              <img class="slider__image_after" src="img/index/slim-cat.png" width="280" height="256" alt="Худой кот">
Ошибка именования класса по БЭМ.

2023-10-19 08:40 UTC, Vital-Sh commented on source/catalog.html
> +      <h1 class="visually-hidden">У нас широкий выбор товаров питания для животных.</h1>
Исправил

2023-10-19 08:41 UTC, Vital-Sh commented on source/catalog.html
> +          <!--Не нравится мне второе имя класса которое придумал у списка, но мне же нужно показать, что этот список является элементом блока navigation и что он является отдельным блоком. Поэтому по
Исправил.

2023-10-19 08:43 UTC, Vital-Sh commented on source/catalog.html
> +      <h2 class="catalog-main-container__title">Каталог продукции</h2>
Исправил.

2023-10-19 08:57 UTC, Vital-Sh commented on source/catalog.html
> +      <!--Не уверен нужно ли тут миксование классов списка, а так же обёртка и отдельный заголовок...-->
Исправил.

2023-10-19 09:20 UTC, Vital-Sh commented on source/catalog.html
> +        <!--Вопрос по макету... Должно ли что-то происходить при нажатие на картинку (приближение, попап и т.п.)?-->
Исправил.

2023-10-19 10:00 UTC, Vital-Sh commented on source/catalog.html
> +            <dt class="goods-description__value">700</dt>
Исправил.

2023-10-19 10:04 UTC, Vital-Sh commented on source/catalog.html
> +              <a class="site-nav-list__link site-nav-list__item--active" href="catalog.html">
Исправил.

2023-10-19 10:16 UTC, Vital-Sh commented on source/catalog.html
> +          <button class="card__button" type="button">заказать</button>
Исправил.

2023-10-19 10:19 UTC, Vital-Sh commented on source/catalog.html
> +            <!--Значёк рубля будет реализован изображением, или можно вставить текстом из макета?-->
Исправил.

2023-10-19 10:34 UTC, Vital-Sh commented on source/catalog.html
> +      <!--Решил вынести кнопки "Ещё" из списка, чтобы у людей, которые пользуются читалками, имелась возможность сразу открыть более полный список продуктов, а не толкьо после того, как прослушают ин
Пока оставил как есть. Нужно уточнение.

2023-10-19 11:29 UTC, Vital-Sh commented on source/catalog.html
> +      <article class="catalog-main-container__show-more show-more-wrapper">
Отложил, до проведения консультации.

2023-10-19 12:11 UTC, Vital-Sh commented on source/catalog.html
> +        <button class="show-more-wrapper__button-more" type="button">Показать еще 100500 товаров</button>
Нужен совет. Отложил до консультации.

2023-10-19 12:11 UTC, Vital-Sh commented on source/catalog.html
> +            </dl>
Исправил.

2023-10-19 12:17 UTC, Vital-Sh commented on source/catalog.html
> +            <button class="additional-card__button">заказать</button>
Исправил.

2023-10-19 12:17 UTC, Vital-Sh commented on source/catalog.html
> +        <!--Вопрос по макету. Когда должен ещё отображаться товар? После нажатия на крест, на текст "Показать еще 100500 товаров", текст "На самом деле вкусов гораздо больше!", или это всё одна больш
Нужно уточнение. Отложил до консультации.

2023-10-19 12:24 UTC, Vital-Sh commented on source/catalog.html
> +      <aside class="catalog-main-container__promo promo-gift">
Исправил, но нужен совет.

2023-10-19 12:27 UTC, Vital-Sh commented on source/catalog.html
> +        <!--Вопрос по макету. Это просто картинка с рекламой? Ссылка на страницу, где все товары в корзине? Или кнопка, которая добавляет все товары в корзину? Если кнопка, то при нажатии на что она
Исправил.

2023-10-19 12:31 UTC, Vital-Sh commented on source/catalog.html
> +        <h2 class="visually-hidden">Как нас найти?</h2>
Предположил, что это замечание к строке кода - <button class="promo-gift__button">Закажите все и получите чехол для кота в подарок!</button>. Исправил на тег <p>. Если это была ошибка в другой строчке кода, то поясните к какой именно...

2023-10-19 12:33 UTC, Vital-Sh commented on source/catalog.html
> +        <iframe class="contacts__map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6036257198189!2d30.320472477349337!3d59.938719162093555!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3
Это нужно делать сейчас, на этапе разметки? Или будет реализовано уже при построении сеток?

2023-10-19 12:37 UTC, Vital-Sh commented on source/catalog.html
> +        </a>
В мобильной версии сайта между текстом логотипа Академии и иконкой логотипа Академии много пустого пространства. Чтобы не было изменения курсора при наведении на это пустое пространство я и разделил блок с ссылкой на два объекта. Если это лишнее, то переделаю в одну.

2023-10-19 12:46 UTC, Vital-Sh commented on source/catalog.html
> +        <ul class="add-list-wrapperr__additional-list additional-cards">
Исправил.

2023-10-19 12:58 UTC, Vital-Sh commented on source/catalog.html
> +      <aside class="main-container__contacts contacts">
Исправил, но нужно уточнение.

2023-10-19 13:02 UTC, Vital-Sh commented on source/catalog.html
> +    <footer class="mail-footer">
Исправил.

2023-10-19 13:04 UTC, Vital-Sh commented on source/form.html
> +    <h1 class="visually-hidden">У нас широкий выбор товаров питания для животных.</h1>
Исправил.

2023-10-19 13:04 UTC, Vital-Sh commented on source/form.html
> +    <!--Возможно нет смысла на каждую страницу задавать разные классы для main. Пока назвал их по-разному, если в процессе вёрстки страниц не будет различий для main, то название класса будет одинако
Нужен совет. Отложил до консультации.

2023-10-19 13:05 UTC, Vital-Sh commented on source/form.html
> +      <h1 class="visually-hidden">Кэт энерджи - заботу о весе вашего любимца мы берём на себя.</h1>
Исправил.

2023-10-19 13:06 UTC, Vital-Sh commented on source/form.html
> +      <h2 class="form-main-container__title">Подбор программы</h2>
Исправил.

2023-10-19 13:06 UTC, Vital-Sh commented on source/form.html
> +            <input class="cat-information__age-input" type="text" name="cat-age" placeholder="7" required>
Исправил.

2023-10-19 13:11 UTC, Vital-Sh commented on source/form.html
> +          <!--У нас в макете 3 одинаковых по оформлению элемента отличаются только текстом...
Оставил до раздела со стилизацией пока так.

2023-10-19 13:28 UTC, Vital-Sh commented on source/form.html
> +            <input class="owner-information__phone-number-input" type="text" name="owner-phone-number" placeholder="8 (960) 900-60-90" required>
Исправил.

2023-10-19 13:29 UTC, Vital-Sh commented on source/img/index/Fat-cat.png
Исправил.

2023-10-19 13:34 UTC, Vital-Sh commented on source/form.html
> +                <span class="control_label">сахарозаменитель</span>
Исправил.

2023-10-19 13:35 UTC, Vital-Sh commented on source/index.html
> +        <p class="promo-wrapper__intro">Функциональное питание для котов</p>
Исправил.

2023-10-19 13:35 UTC, Vital-Sh commented on source/index.html
> +    <h1 class="visually-hidden">У нас широкий выбор товаров питания для животных.</h1>
Исправил.

2023-10-19 13:37 UTC, Vital-Sh commented on source/index.html
> +        <!--Я правильно понял, что при переключении между разными устройствами положение кнопки будет меняться наложение поверх изображения и дублировать её (как дублировали при вёрстке "Барбершопа")
Если подразумевается два одинаковых тега <p> с разным содержимым, то исправил.

2023-10-19 13:38 UTC, Vital-Sh commented on source/index.html
> +      <h1 class="visually-hidden">Кэт энерджи - заботу о весе вашего любимца мы берём на себя.</h1>
Исправил.

2023-10-19 13:44 UTC, Vital-Sh commented on source/index.html
> +      <section class="main-container__about-weight servic">
Описка... Исправил.

2023-10-19 13:46 UTC, Vital-Sh commented on source/index.html
> +          <img class="weight-loss__image" src="img/index/silhouette-cat-slim.svg" width="36" height="50" alt="Силуэт сидящей египетской кошки в ошейнике">
Исправил.

2023-10-19 13:46 UTC, Vital-Sh commented on source/index.html
> +          <img class="weight-gain__image" src="img/index/silhouette-panther.svg" width="67" height="28" alt="Силуэт идущей пантеры">
Исправил.

2023-10-19 13:47 UTC, Vital-Sh commented on source/index.html
> +      <!--Неуверен на счёт правильного выбора тега... Возможно тут использовать тег article? По идее этот блок можно на любую другую страницу поместить, но тогда не сосвсем будет понятен смысл текста
Исправил.

2023-10-19 13:49 UTC, Vital-Sh commented on source/index.html
> +          <!--Я же правильно понимаю, что в этом слайдере порядок сладдов фиксирован и важен? Или тут всё же использовать ненумерованный?-->
Исправил.

2023-10-19 13:56 UTC, Vital-Sh commented on source/index.html
> +          <!--Данный слайдер переключается не кнопками, а ползунком... Нужно ли сейчас заниматься вёрсткой этого элемента, или работа со слайдером будет продолжена в следующих разделах?-->
Нужен более развёрнутый ответ. Отложил до консультации.

2023-10-19 13:57 UTC, Vital-Sh commented on source/index.html
> +            <dt class="service-result-list_benefit">
Исправил.

2023-10-19 13:59 UTC, Vital-Sh commented on source/index.html
> +              <img class="slider__image_before" src="img/index/Fat-cat.png" width="280" height="256" alt="Толстый кот">
Исправил.

2023-10-19 13:59 UTC, Vital-Sh commented on source/index.html
> +              <img class="slider__image_after" src="img/index/slim-cat.png" width="280" height="256" alt="Худой кот">
Исправил.

2023-10-23 16:14 UTC, Vital-Sh commented on source/catalog.html
> +      <!--Решил вынести кнопки "Ещё" из списка, чтобы у людей, которые пользуются читалками, имелась возможность сразу открыть более полный список продуктов, а не толкьо после того, как прослушают ин
Использовал div для общего контейнера, а article для вёрстки карточек. Теперь при проверке на валидаторе он мне выдаёт на каждую карточку предупреждение (Article lacks heading. Consider using h2-h6 elements to...), а изменить тег p с названием карточки на h2 нельзя, т.к. p в данном случае - часть ссылки. Не обращать на это внимание? В каждую карточку добавить скрытый h2? Обернуть ссылку в h2?

2023-10-24 16:12 UTC, andreysgra commented on source/catalog.html
> +      <!--Решил вынести кнопки "Ещё" из списка, чтобы у людей, которые пользуются читалками, имелась возможность сразу открыть более полный список продуктов, а не толкьо после того, как прослушают ин
Это не ошибка, а предупреждение. А главное, почему нельзя параграф `product-card__text` преобразовать в `h2`? Можно, ничего в этом плохого нет.

2023-10-24 16:23 UTC, andreysgra requested changes

2023-10-24 16:23 UTC, andreysgra commented on source/index.html
> +          <iframe class="our-contacts__map--scalability" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6036257198189!2d30.320472477349337!3d59.938719162093555!2m3!1f0!2f0!3f0!3m2!1i
`our-contacts__map--scalability` - класс модификатора не может использоваться без класса элемента. Ошибка на всех трёх страницах.

2023-10-24 16:23 UTC, andreysgra commented on source/index.html
> +          <img class="our-contacts__map--background" src="img/catalog/our-location.jpg" width="320" height="362" alt="Карта с отметкой где находится офис компании">
`our-contacts__map--background` - класс модификатора не может использоваться без класса элемента.  Ошибка на всех трёх страницах.

2023-10-24 16:23 UTC, andreysgra commented on source/index.html
> +        </ul>
Только по одному приведённому тексту не стоит судить, текст может быть другой, более содержательный. Я бы использовал `ol`.

2023-10-26 14:46 UTC, Vital-Sh commented on source/index.html
> +          <iframe class="our-contacts__map--scalability" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6036257198189!2d30.320472477349337!3d59.938719162093555!2m3!1f0!2f0!3f0!3m2!1i
Понял в чём ошибся. Исправил.

2023-10-26 14:46 UTC, Vital-Sh commented on source/index.html
> +          <img class="our-contacts__map--background" src="img/catalog/our-location.jpg" width="320" height="362" alt="Карта с отметкой где находится офис компании">
Понял в чём ошибся. Исправил.

2023-10-26 14:47 UTC, Vital-Sh commented on source/index.html
> +        </ul>
Доверюсь вашему опыту. Исправил.

2023-10-26 15:07 UTC, Vital-Sh commented on source/catalog.html
> +      <!--Решил вынести кнопки "Ещё" из списка, чтобы у людей, которые пользуются читалками, имелась возможность сразу открыть более полный список продуктов, а не толкьо после того, как прослушают ин
По техническому заданию к странице каталога пункт 6.1 параграф с классом product-card__text и рисунок товара является частью ссылки, а h2 нельзя вкладывать в ссылку. Вот я и не знаю как поступить, чтобы соблюсти это требование технического задания.

2023-10-26 16:45 UTC, Vital-Sh commented on source/catalog.html
> +      <!--Решил вынести кнопки "Ещё" из списка, чтобы у людей, которые пользуются читалками, имелась возможность сразу открыть более полный список продуктов, а не толкьо после того, как прослушают ин
<article class="product-card">
          <a class="product-card__link product-card__link--image" href="#">
            <img class="product-card__image" src="img/catalog/card-3.png" width="140" height="107" alt="Корм для кошек Cat Energy PRO 500 г со вкусом рыбы">
          </a>
          <h2 class="product-card__title">
            <a class="product-card__link product-card__link--text" href="#">Cat Energy PRO 500 г</a>
          </h2>
Если подобным образом разметить карточку товара, то валидатор перестаёт ругаться. Нашёл вот такой способ, он приемлим? Изменить все карточки подобным образом?

2023-10-27 08:03 UTC, merged